"""Add name and location to Marathon model

Revision ID: 333d99d28861
Revises: 4fa07a4f391b
Create Date: 2025-02-11 19:30:47.176619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333d99d28861'
down_revision = '4fa07a4f391b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('marathon_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathons', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('name')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('marathon_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
